### PR TITLE
Add support for excluding tags

### PR DESCRIPTION
**Pull request by ideasman42**
This is needed so cycling tags works with a scratch buffer, see: https://codeberg.org/river/wiki/src/branch/master/pages/Scratchpad-and-Sticky.md

### CODE REVIEW

**Comment by NickHastings** [comment]
I think I understand the intent of this, but as implemented it seems to do something different. Lets say I have just tag 1 focused and I want to skip tag 2, and go directly to tag 3. I would think to run
```
cycle-focused-tags -m 2 next
```
However it moves to tag 2, not 3.

**Comment by ideasman42** [comment]
The mask isn't a way of skipping tags, it's a way of ignoring a tag entirely and not taking it into account when cycling.

If you use the scratchpad functionality it works as follows.

- Some windows can be sent to the scratchpad (e.g. `1 << 20`).
- The scratchpad can be toggled on/off.

This conflicts with the `riverwm-utils` cycling logic because cycling tags once the scratchpad is visible is interpreting `river` as having 20 tags (I think) ... so cycling moves through all the tags until it reaches 20. At least without masking the scratchpad I end up cycling through many empty tags.

This isn't useful, the scratchpad is used as a toggle, not a slot that's cycled through. So in this case I think it makes sense to mask it out, perform cycling, then add it back.

----

Excluding tags seems like it could be a separate feature, although I don't see the need for it personally.

**Comment by NickHastings** [comment]
I use a scratch pad on tag 20, and uses tags 1 - 9 in the "normal" way. I make cycle-focus-tags ignore it by calling it with a n_tags option like `cycle-focused-tags next 9`. If I wanted the scratchpad to be included I guess I would put it on 10 and use `cycle-focused-tags next 10`. Can you not achieve what you want using one of those approaches?

Note that if you don't use an n_tags option it will assume you are using all 32 tags.

**Comment by ideasman42** [comment]
I use the `n_tags` option, double checked and there is for sure strange bugs going on without the scratchpad masking logic from this PR.

The problem looks to be caused by the current tags (including the scratchpad) being bit-shifted then used to create the next tag.

Snip:
```
    tags = SEAT.focused_output.focused_tags
    ...
        new_tags |= (tags << 1)
        ... or ...
        new_tags |= (tags >> 1)
    ...
    CONTROL.add_argument("set-focused-tags")
    CONTROL.add_argument(str(new_tags))
    CONTROL.run_command(SEAT.wl_seat)
```

This logic is including the scratchpad but shifted to enable a new tag around the upper bits which then causes odd behavior when new windows are created. I ran into problems where cycling windows would mostly cycle my tags - then sometimes show another window (once in 32 times ... at a guess).

**Comment by NickHastings** [comment]
If the scratch pad is on a pad number higher than n_tags then `cycle-focus-tags` *should* (but perhaps does not currently) ignore it without the need to pass a -m option.

**Comment by ideasman42** [comment]
> If the scratch pad is on a pad number higher than n_tags then `cycle-focus-tags` _should_ (but perhaps does not currently) ignore it without the need to pass a -m option.

It probably does ignore it - when it comes to it's own counting logic, however the scratchpad bits are being set:

I only use two workspaces and this is a print of the flag as they're cycled when the scratchpad is masked out.

```
0b1 1                                                                                                                                                                                               
0b10 2                                                                                                                                                                                              
0b1 1                                                                                                                                                                                               
0b10 2                                                                                                                                                                                              
0b1 1                                                                                                                                                                                               
0b10 2                                                                                                                                                                                              
0b1 1                                                                                                                                                                                               
0b10 2                                                                                                                                                                                              
0b1 1                                                                                                                                                                                               
```

Without the masking, this is what happens:

```
0b10 2                                                                                                                                                                                                                 
0b11000000000000000000001 6291457                                                                                                                                                                                      
0b110000000000000000000010 12582914                                                                                                                                                                                    
0b1100000000000000000000001 25165825                                                                                                                                                                                   
0b11000000000000000000000010 50331650                                                                                                                                                                                  
0b110000000000000000000000001 100663297                                                                                                                                                                                
0b1100000000000000000000000010 201326594                                                                                                                                                                               
0b11000000000000000000000000001 402653185                                                                                                                                                                              
0b110000000000000000000000000010 805306370                                                                                                                                                                             
0b1100000000000000000000000000001 1610612737                                                                                                                                                                           
0b11000000000000000000000000000010 3221225474                                                                                                                                                                          
0b110000000000000000000000000000001 6442450945                                                                                                                                                                         
0b110000000000000000000000000000001 6442450945                                                                                                                                                                         
0b110000000000000000000000000000001 6442450945                                                                                                                                                                         
0b110000000000000000000000000000001 6442450945                                                                                                                                                                         
0b110000000000000000000000000000001 6442450945                                                                                                                                                                         
0b110000000000000000000000000000001 6442450945                                                                                                                                                                         
0b1100000000000000000000000000001 1610612737                                                                                                                                                                           
0b110000000000000000000000000010 805306370                                                                                                                                                                             
0b11000000000000000000000000001 402653185                                                                                                                                                                              
0b1100000000000000000000000010 201326594                                                                                                                                                                               
0b11000000000000000000000000001 402653185                                                                                                                                                                              
0b110000000000000000000000000010 805306370                                                                                                                                                                             
0b1100000000000000000000000000001 1610612737                                                                                                                                                                           
0b11000000000000000000000000000010 3221225474                                                                                                                                                                          
0b1100000000000000000000000000001 1610612737                                                                                                                                                                           
0b110000000000000000000000000010 805306370                                                                                                                                                                             
0b11000000000000000000000000001 402653185                                                                                                                                                                              
0b1100000000000000000000000010 201326594                                                                                                                                                                               
0b110000000000000000000000001 100663297                                                                                                                                                                                
0b11000000000000000000000010 50331650                                                                                                                                                                                  
0b1100000000000000000000001 25165825                                                                                                                                                                                   
0b110000000000000000000010 12582914                                                                                                                                                                                    
0b11000000000000000000001 6291457                                                                                                                                                                                      
0b1100000000000000000010 3145730                                                                                                                                                                                       
0b110000000000000000001 1572865                                                                                                                                                                                        
0b11000000000000000010 786434                                                                                                                                                                                          
0b1100000000000000001 393217                                                                                                                                                                                           
0b110000000000000010 196610                                                                                                                                                                                            
0b11000000000000001 98305                                                                                                                                                                                              
0b1100000000000010 49154                                                                                                                                                                                               
0b110000000000001 24577                                                                                                                                                                                                
0b11000000000010 12290                                                                                                                                                                                                 
0b1100000000001 6145                                                                                                                                                                                                   
0b110000000010 3074                                                                                                                                                                                                    
0b11000000001 1537                                                                                                                                                                                                     
0b1100000010 770                                                                                                                                                                                                       
0b110000001 385                                                                                                                                                                                                        
0b11000010 194                                                                                                                                                                                                         
0b1100001 97                                                                                                                                                                                                           
0b110010 50                                                                                                                                                                                                            
0b11001 25                                                                                                                                                                                                             
0b1110 14                                                                                                                                                                                                              
0b111 7                                                                                                                                                                                                                
0b11 3                                
```

**Comment by NickHastings** [comment]
Thanks for the extra information. I think I now understand. It seems I have only very infrequently actually making use of the scratch pad so didn't notice the problem.

I merged your PR on the commandline since there were some conflicts with some recent changes that I made.

However I'm thinking a cleaner solution is to mask out all the tags above n_tags, by default. Eg
replace the commandline option in your PR to: 

```
used_tags = (1<<n_tags) - 1
all_tags  = (1<<32) - 1
tag_mask = all_tags^used_tags
```

I've actually already made and tested this change but didn't push it yet.
What do you think?

**Comment by ideasman42** [comment]
> ```
> used_tags = (1<<n_tags) - 1
> all_tags  = (1<<32) - 1
> tag_mask = all_tags^used_tags
> ```
> 
> I've actually already made and tested this change but didn't push it yet. What do you think?

This seems a better solution (my change assumed that someone _might_ not want to do this) but I can't see a reason to ever manipulate higher bits. So LGTM.

Note that I was thinking of having a way to always disable the scratchpad when cycling, since it can be annoying - but that could be it's own command-line-option: to disable any higher bits instead of re-applying them.

**Comment by NickHastings** [comment]
> Note that I was thinking of having a way to always disable the scratchpad when cycling, since it can be annoying

I think I agree with you. I'll do it that way.

> - but that could be it's own command-line-option: to disable any higher bits instead of re-applying them.

If someone wants the opposite behaviour it can be added as an option.

**Comment by ideasman42** [comment]
Sounds good, I'm not that fussed - optionally keep scratchpad seems fine too.

**Comment by ideasman42** [comment]
Note that a more robust method could be to select the rightmost bit, so if there is ever more than one bit set, it picks the lowest and shifts that.

This means there is never the problem of additional bits being shifted up and down. e.g. `tags = tags & -tags`

https://stackoverflow.com/questions/56358931/how-to-find-the-leftmost-bit-of-an-number-in-one-line

**Pull request closed without merging**
